server:
  port: 8888
spring:
  config:
    activate:
      on-profile: local, dev, prod
  application:
    name: config-service
  cloud:
    bus:
      kafka:
        destination: config-topic
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/lotteon2/BB-CONFIG.git
          username: ${github.username}
          password: ${github.token}
management:
  endpoints:
    web:
      exposure:
        include:
          - "refresh"
          - "bus-refresh"
          - "health
encrypt:
  key: ${secret}
logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
