spring:
  cloud:
    stream:
      kafka:
        binder:
          default-broker-port: localhost:9092
          brokers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}